# Generated by Django 6.0.1 on 2026-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Paste YouTube trailer link', null=True),
        ),
    ]
