# Generated by Django 6.0.1 on 2026-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_booking_amount_booking_payment_id_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=199, max_digits=6),
        ),
    ]
