# Generated by Django 6.0.1 on 2026-04-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_seatreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.seatreservation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seat'),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='movies.seat'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('seat', 'showtime')},
        ),
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together={('seat', 'showtime')},
        ),
    ]
