# Generated by Django 6.0.1 on 2026-04-23 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_booking_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='movies_book_status_5cd60b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['showtime'], name='movies_book_showtim_852d63_idx'),
        ),
    ]
