# Generated by Django 6.0.1 on 2026-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_booking_movies_book_booked__a7ab7e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, help_text='Paste a direct image URL', null=True),
        ),
    ]
